### ISSUE TITLE
`/info` と `/help` コマンドを実行するとエラー

### ISSUE THREAD

**Issue by private-yusuke** [private-yusuke/botot2#97]
# 概要

`/info` や `/help` コマンドを実行するとエラーが発生する。

## 影響範囲

少なくとも現在の master の最新のコミット https://github.com/private-yusuke/botot2/commit/193480778da7ead04803a7a6c6d369cefafb4575 の時点でエラーが発生する

## 原因

https://github.com/private-yusuke/botot2/blob/193480778da7ead04803a7a6c6d369cefafb4575/src/index.ts#L24

ここで各モジュールのコンストラクタに渡している `ai` が `undefined` になっている。

このため、`/info`, `/help` のそれぞれ以下の箇所で TypeError が発生している。

https://github.com/private-yusuke/botot2/blob/193480778da7ead04803a7a6c6d369cefafb4575/src/modules/admin.ts#L40

https://github.com/private-yusuke/botot2/blob/193480778da7ead04803a7a6c6d369cefafb4575/src/modules/admin.ts#L54

## 解決方法

https://github.com/private-yusuke/botot2/pull/72#discussion_r974130418 では、AdminModule の constructor には初期化された Ai のインスタンスへの参照を渡すことを想定していたようだった。

これをするためには、AdminModule よりも先に Ai のインスタンスを作成する必要がある。

そのために、現在 `src/index.ts` で行っているモジュールの初期化処理を `Ai.init()` 内で実行するように処理を引っ越して、AdminModule のインスタンスにはそのブロック内で `this` を渡すという方法を考えている。

## エラー

<details>
<summary>/info を実行したときのエラー</summary>

```
/[REDACTED]/built/modules/admin.js:44
Modules: ${this.ai.modules.map((i) => `${i.name}(${i.priority})`).join(", ")}
                   ^

TypeError: Cannot read properties of undefined (reading 'modules')
    at AdminModule.<anonymous> (/[REDACTED]/built/modules/admin.js:44:20)
    at Generator.next (<anonymous>)
    at /[REDACTED]/built/modules/admin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/[REDACTED]/built/modules/admin.js:4:12)
    at AdminModule.onCommand (/[REDACTED]/built/modules/admin.js:41:16)
    at Ai.<anonymous> (/[REDACTED]/built/ai.js:199:46)
    at Generator.next (<anonymous>)
    at fulfilled (/[REDACTED]/built/ai.js:5:58)
```
</details>

<details>
<summary>/help を実行したときのエラー</summary>

```
/[REDACTED]/built/modules/admin.js:59
                this.ai.modules.forEach((v) => {
                        ^

TypeError: Cannot read properties of undefined (reading 'modules')
    at AdminModule.<anonymous> (/[REDACTED]/built/modules/admin.js:59:25)
    at Generator.next (<anonymous>)
    at /[REDACTED]/built/modules/admin.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/[REDACTED]/built/modules/admin.js:4:12)
    at AdminModule.onCommand (/[REDACTED]/built/modules/admin.js:41:16)
    at Ai.<anonymous> (/[REDACTED]/built/ai.js:199:46)
    at Generator.next (<anonymous>)
    at fulfilled (/[REDACTED]/built/ai.js:5:58)
```
</details>

**Comment by azarashi2931** [comment]
あー、これは俺のせいっぽいな
みます
